### ISSUE TITLE
get_item_list has an array access issue

### ISSUE THREAD

**Issue by javorszky** [wp-cli/extension-command#231]
## Bug Report

This is not a duplicate of #209, or rather I've gone through that one, looked at the fix, verified that the fix is on the master branch, and thus more than likely deployed, and yet the issue still (again) persists.

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Running `wp plugin list` while in a site with a custom plugin that's not in the repository causes the following notice:

```
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
```
I suspect not much has changed, a complete trace is on #209.

**Describe how other contributors can replicate this bug**

Create a completely new WP site and add a noop custom plugin:

```
$ mkdir 231-repro-wp
$ cd 231-repro-wp
$ wp core download
Downloading WordPress 5.4.1 (en_US)...
Using cached file '/Users/javorszky/.wp-cli/cache/core/wordpress-5.4.1-en_US.tar.gz'...
Success: WordPress downloaded.
$ wp core config --dbname=issue-231
Success: Generated 'wp-config.php' file.
$ wp db create
Success: Database created.
$ wp core install --url=https://test231.test
Success: WordPress installed successfully.
$ touch wp-content/plugins/bug-plugin.php
<<edit the plugin file here>>
```

Plugin file content:
```
<?php
/**
 * Plugin Name:       Bug plugin
 * Description:       Plugin that produces a bug
 * Author:            Gabor Javorszky
 * Author URI:        https://javorszky.co.uk
 * Version:           1.0.0
 * Requires at least: 4.4
 * Tested up to:      5.4
 */

add_action( 'init', function() {
    // actually do nothing.
} );
```

And then list the plugins:
```
$ wp plugin list
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
+------------+----------+--------+---------+
| name       | status   | update | version |
+------------+----------+--------+---------+
| akismet    | inactive | none   | 4.1.5   |
| bug-plugin | inactive | none   | 1.0.0   |
| hello      | inactive | none   | 1.7.2   |
+------------+----------+--------+---------+
```

**Describe what you would expect as the correct outcome**

The php notices should really not be there.

**Let us know what environment you are running this on**

```
OS:	Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/7.4.5_2/bin/php
PHP version:	7.4.5
php.ini used:	/usr/local/etc/php/7.4/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/javorszky/Sites/wpcli-plugin-bug
WP-CLI packages dir:
WP-CLI global config:	/Users/javorszky/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Provide a possible solution**

`isset( $arrayname['offset'] )` will still fail if `$arrayname` is not actually an array.

```
$ wp shell
wp> $arrayname = null;
=> NULL
wp> echo $arrayname['offset'];
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/shell-command/src/WP_CLI/Shell/REPL.php(32) : eval()'d code on line 1
Notice: Trying to access array offset on value of type null in phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/shell-command/src/WP_CLI/Shell/REPL.php(32) : eval()'d code on line 1
wp>
```

I would welcome @dsifford 's original idea of checking the type of the variable.

Alternatively the default value should be an empty array instead of null at the end of line 650: https://github.com/wp-cli/extension-command/blob/master/src/Plugin_Command.php#L650

## edit: Theme_Command.php
This also happens in the theme command [here](https://github.com/wp-cli/extension-command/blob/master/src/Theme_Command.php#L466-L479)

**Comment by topher1kenobe** [comment]
@javorszky why does this only happen with a brand new install of WP?

**Comment by javorszky** [comment]
I don't think it *only* happens with a brand new install of WP, but a brand new install of WP is a great way to isolate the problem to make sure that it's not being caused by whatever else I might have in the site (other plugins / other themes / content).

**Comment by voldemortensen** [comment]
For the record, it has been released in v2.0.8 (See: https://github.com/wp-cli/extension-command/releases)

**Comment by javorszky** [comment]
Yes, I know, I checked and double checked. And yet in extension-command 2.0.9 (current latest) this is still (again) a problem, unless wpcli 2.4.0 does not contain version 2.0.8+ of the extension-command.

**Comment by voldemortensen** [comment]
> ... I've gone through that one, looked at the fix, verified that the fix is on the master branch, and thus more than likely deployed, and yet the issue still (again) persists.

This made is seem like you weren't sure. Just trying to provide context.

**Comment by javorszky** [comment]
> This made is seem like you weren't sure. Just trying to provide context.

I provided that to signal that I'm not opening an issue blindly. To make it clear that I have checked, double checked, verified, and reproduced the issue on the latest versions of everything.

I hoped to avoid conversations about "but we already fixed it". How should I have worded it so this intention came across?

**Comment by voldemortensen** [comment]
I wasn't even trying to indicate that this issue had already been fixed. On the contrary, I was trying to support your issue by saying that the "fix" had been released, but it's still broken.

> I hoped to avoid conversations about "but we already fixed it". How should I have worded it so this intention came across?

Honestly, this one seems like it's on me. It came across that I was countering you when I meant to be supporting you. I should have said something like, "For the record, the supposed fix was released in v2.0.8, but the issue is still in the latest version."

**Comment by javorszky** [comment]
> Honestly, this one seems like it's on me.
Eek, misunderstood, sorry!

**Comment by javorszky** [comment]
I've also added reference to the `Theme_Command.php` when the site contains a custom theme that's not in the .org repository.

**Comment by stephenaiesi** [comment]
Has this been solved? I've read this and 209 and am having the same exact issue.  Everything is up to date and the bug has been reproduced in fresh installs.  I would just ignore it but I'm developing a cli tool for others to use and it really messes up the console logging to have this error for pages and pages.  I have used regex (in node) to filter out the stderr if this message exists, but I really don't like that.

I'm not clear from this thread if the bug is actually fixed, or if it was addressed and still broken and a future release will hopefully address it.

**Comment by schlessera** [comment]
This issue was fixed and should not be reproducible with WP-CLI nightly and will be included in WP-CLI 2.5.0+

The fix is part of `wp-cli/extension-command` v2.0.8+, but WP-CLI v2.4.0 only include `wp-cli/extension-command` v2.0.7.

I'm closing this as a solved issue, and the upcoming v2.5.0 release will hopefully get rid of the problem once and for all.

Note: for anyone still struggling with this, please switch to WP-CLI nightly (`wp cli update --nightly`) until v2.5.0 has been released.
